---
Name: advertisements
Before: 'app/*'
After:
    - 'framework/*'
    - 'cms/*'
---
SiteTree:
  extensions:
    - AdvertisementDecorator


---
Only:
  classexists: 'DataObjectSorterDOD'
---
Advertisement:
  extensions:
    - DataObjectSorterDOD
