---
Name: advertisements
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Sunnysideup\Advertisements\Model\AdvertisementDecorator


---
Only:
  classexists: 'Sunnysideup\DataobjectSorter\DataObjectSorterDOD'
---
Sunnysideup\Advertisements\Model\AdvertisementDecorator:
  extensions:
    - Sunnysideup\DataobjectSorter\DataObjectSorterDOD
