---
Name: advertisements
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Sunnysideup\Advertisements\Model\AdvertisementDecorator

SilverStripe\Admin\LeftAndMain:
    extra_requirements_css:
        - 'sunnysideup/advertisements: client/css/AdvertisementsCMS.css'

---
Only:
  classexists: 'Sunnysideup\DataobjectSorter\DataObjectSorterDOD'
---
Sunnysideup\Advertisements\Model\Advertisement:
  extensions:
    - Sunnysideup\DataobjectSorter\DataObjectSorterDOD
